server:
  port: 8080
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${mysql.addr:8.130.66.80:3306}/oss?useSSL=false&amp&serverTimezone=UTC
      username: ${mysql.username:root}
      password: ${mysql.password:123987}
  redis:
    host: ${redis.ip:127.0.0.1}
    port: ${redis.port:6379}
    timeout: 1000
    password:
    lettuce:
      pool:
        minIdle: 30
        maxIdle: 500
        maxWait: 10000
        maxActive: 500
  application:
    name: oss-service


mybatis-plus:
  global-config:
    db-config:
      table-prefix:
      id-type:
    banner: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true



logging:
  level:
    ccw.serviceinnovation.oss.mapper: info
